---
title: "NY Weather Stations: 2000-2010"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data(ny_noaa)

ny_noaa =
ny_noaa %>%
  drop_na() %>%
  mutate(date2 = date) %>% 
  separate(date2, into = c("year", "month", "day"), sep = "-", convert = TRUE) %>% 
  mutate(
    prcp = prcp*10,
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin),
    tmax = tmax/10,
    tmin = tmin/10,
    year = as.numeric(year)
    ) %>%
    filter(
      id %in% sample(unique(id), 5),
      year >= 2000
    )
```

Column {data-width=650}
-----------------------------------------------------------------------

### Monthly Average Maximum Temperatures (ºC) by Stations
#### Marker Size = Precipitation (mm)

```{r, message = FALSE}
ny_noaa %>% 
  group_by(id, year, month) %>%   
  mutate(
    mean_tmax = round(mean(tmax), digits = 2),
    text_label = str_c("Station ID: ", id, "\nMean Max Temperature: ", mean_tmax, "ºC")
  ) %>%
    plot_ly(
      x = ~date, y= ~mean_tmax, size = ~prcp, color = ~id, text = ~text_label, 
      type = "scatter", mode = "markers"
    ) %>% 
    layout(
      xaxis = list(title = "Date"),
      yaxis = list(title = "Mean Maximum Temperature (ºC)")
    )
```

Column {data-width=350}
-----------------------------------------------------------------------

### Yearly Snowfall (mm) by Stations

```{r}
ny_noaa %>%
  filter(snow > 0) %>% 
  group_by(year) %>% 
  mutate(
    sum_snow = sum(snow),
    text_label = str_c("Station ID: ", id, "\nTotal Snowfall in ", year, ":", sum_snow, "mm")
  ) %>% 
  plot_ly(
    x = ~year, y = ~sum_snow, color = ~id, text = ~text_label, 
    type = "bar", colors = "viridis"
  ) %>% 
  layout(
      xaxis = list(title = "Year"),
      yaxis = list(title = "Sum of Snowfall (mm)")
    )
```

### Temperature Amplitude (ºC) by Stations

```{r}
ny_noaa %>% 
    mutate(
      amplitude = tmax - tmin
    ) %>%
    group_by(id) %>% 
    plot_ly(
      x = ~year, y = ~amplitude, color = ~id, 
      type = "box", alpha = .5, colors = "viridis"
    ) %>% 
    layout(
      xaxis = list(title = "Year"),
      yaxis = list(title = "Temperature Amplitude (ºC)")
    )
```

